services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solid
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: minio_server
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Dashboard
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - storage:/data

volumes:
  data:
  storage:
