[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.14,<3.15"
django = "^6.0"
boto3 = "^1.42.5"
django-storages = "^1.14.6"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
