services:
  database:
    image: postgres:16
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - dev_database:/var/lib/postgresql/data

  storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: storage
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Dashboard
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - dev_storage:/data

volumes:
  dev_database:
  dev_storage:
