services:
  database:
    image: postgres:16
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - test_data:/var/lib/postgresql/data

  storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: storage
    ports:
      - "9001:9000"   # API S3
      - "9002:9001"   # Dashboard
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - test_storage:/data

volumes:
  test_data:
  test_storage:
